const MEDIA_BASE_URL = 'https://media.qvapay.com'

/**
 * Absolute URL for an asset on the QvaPay CDN (media.qvapay.com).
 *
 * The backend sometimes returns paths with a leading slash (e.g.
 * `/operators/claro-com.png`, generated by resolveBrandLogo in qpweb);
 * concatenating those onto the base produces a double slash and S3 answers
 * 403 — hence the normalization here. Already-absolute http(s) URLs pass
 * through untouched.
 *
 * @param {string|null|undefined} path - CDN-relative path or absolute URL.
 * @returns {string|null} Absolute URL, or null for empty input.
 */
export function mediaUrl(path) {
	if (!path) return null
	if (path.startsWith('http')) return path
	return `${MEDIA_BASE_URL}/${path.replace(/^\/+/, '')}`
}
