name: mobile_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^7.2.1
  cached_network_image: ^3.1.0
  dartz: ^0.10.0-nullsafety.1
  data_connection_checker: ^0.3.4
  dio: ^4.0.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.1
  flutter_secure_storage: ^4.2.1
  formz: ^0.4.0
  get_it: ^7.2.0
  grouped_list: ^4.0.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  http: ^0.13.3
  hydrated_bloc: ^7.1.0
  intl: ^0.17.0
  json_annotation: ^4.3.0
  path_provider: ^2.0.5
  pin_code_fields: ^7.3.0
  qvapay_api_client:
    git:
      url: https://github.com/qvapay/qvapay_api_client.git
      ref: 5cfd1761042a5c169e67aea71edd6a66aeebdf32

dev_dependencies:
  bloc_test: ^8.3.0
  build_runner: ^2.1.4
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.1
  mocktail: ^0.1.0
  very_good_analysis: ^2.3.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/avatars/
    - assets/images/
    - assets/pay_icons/
    - assets/onboarding/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
